### ISSUE TITLE
[Documentation] Function is improperly documented

### ISSUE THREAD

**Issue by Rudedog9d** [ameily/pypsi#27]
The `Table` class in ` pypsi/pypsi/format.py` has this function:
```
    def extend(self, *args):
        '''
        Add multiple rows to the table, each argument should be a list of
        column values.
        '''
        for row in args:
            self.append(*row)
        return self
```

I think you meant 'A list of ROW values' here?

**Comment by ameily** [comment]
I think I documentation is correct. Each item in the `*args` list needs to be a tuple/list of column values (so *args is a list of lists). For example, the following would add two new rows to the table, each with three columns:

```python
table.extend(
    ('R1C1', 'R1C2', 'R1C3'),
    ('R2C1', 'R2C2', 'R2C3')
)
```

**Comment by Rudedog9d** [comment]
My bad. I read that wrong multiple times
