### ISSUE TITLE
Cannot Tab Complete Subcmd Arguments

### ISSUE THREAD

**Issue by austinbenincasa** [ameily/pypsi#48]
## Info
Pypsi Version: `1.4.5`
Python Version: `3.6`
OS: `CentOS 7.6.1810`

## Description

While using subcmds I am unable to receive tab completions from `command_completer` for subcmd options. Even if I manually return a list of arguments from `complete` like ['--h', '-l', '--lines'] I will only ever receive a `-` on sysout. Seems to be a issue with `command_completer` and also how suggestions are displayed to the screen.

## Example Code
```
class LogCommand(Command):

    def __init__(self, topic='dread', name='log', brief=HelpTopic, **kwargs):
        self.parser = PypsiArgParser(
            prog=name,
            description=brief,
            usage=LogCmdUsage
        )
        self._subcmd = self.parser.add_subparsers(
            dest='subcmd',
            metavar='display'
        )
        self._subcmd.required = True
        display = self._subcmd.add_parser(
            'display', help='prints the log file to the terminal'
        )
        display.add_argument(
            '-l', '--lines', help='prints out a range of lines <start_line>:<end_line>', metavar="LINES", required=False
        )
        super(LogCommand, self).__init__(
            name=name, usage=self.parser.format_help(), topic=topic,
            brief=brief, **kwargs
        )
    def complete(self, shell, args, prefix):
        from pypsi.completers import command_completer
        return command_completer(self._subcmd, shell, args, prefix)

```

**Comment by ameily** [comment]
I think you need to adjust the `complete()` method slightly. Try this to see if it resolves the issue:

```python
def complete(self, shell, args, prefix):
    if len(args) == 1 and args[0].startswith('-'):
        completions = command_completer(self.parser, shell, args, prefix)
    else:
        completions = command_completer(self._subcmd, shell, args, prefix)
    return completions
```

**Comment by austinbenincasa** [comment]
Still does not seem to work. I think the issue has to do with `command_completer`

https://github.com/ameily/pypsi/blob/a62b4f0418be392bf0d3a4d6509ae44412c231c5/pypsi/completers.py#L61

The self._subcmd does not have a attr 'choices' and it is not a `PyPsiArugumentParser` therefore it will always return [] in line 82. Arguments for self._parser can be retrieved by using `.get_options` on the object

https://github.com/ameily/pypsi/blob/a62b4f0418be392bf0d3a4d6509ae44412c231c5/pypsi/completers.py#L61-L77

**Comment by ameily** [comment]
I copy/pasted you code and it appears to be working for me:

![image](https://user-images.githubusercontent.com/749571/74392357-d2026800-4dd4-11ea-9121-1b8c4fcb7e26.png)

The last line I did `log --h<tab>` and it completed to `--help`.

Can you check your completer delims and make sure that the readline completer is set properly (it should be set to a bound method in your Shell class):

```python
import readline
print('readline delims:', readline.get_completer_delims())
print('readline completer:', readline.get_completer())
```

I am testing on Windows so I'll try on Linux later to see if this is an inconsistency of pyreadline on Windows.

**Comment by austinbenincasa** [comment]
This is my output after running the prints() in `on_cmdloop_begin`
```
readline delims:  	
`~!@#$%^&*()-=+[{]}\|;:'",<>/?
readline completer: <bound method Shell.complete of <cli.shell.TestShell object at 0x7f1001a0b438>>
```

**Comment by ameily** [comment]
The issue may be that you have `-` in your completer delims. Can you try

```python
readline.set_completer_delims('\t\n`~!@#$%^&*()=+[{]}\|;:'",<>/?')
```

**Comment by austinbenincasa** [comment]
Looks like the delims was the issue. Tab complete seems to be working now. Thanks boss man!
